/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoplanificadores;

import com.sun.istack.internal.logging.Logger;
import static java.lang.Integer.parseInt;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JOSELINE
 */
public class SJFNoExpropiativo extends javax.swing.JFrame {

    public int proceso;

    /**
     *
     */
    public SJFNoExpropiativo() {
        initComponents();
        this.setLocationRelativeTo(null);
        proceso = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("SJF NO EXPROPIATIVO");

        jLabel2.setText("TIEMPO LLEGADA");

        jLabel3.setText("RÁFAGA");

        jButton1.setText("INSERTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N. PROCESOS", "TIEMPO LLEGADA", "RÁFAGA", "ESTADO"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("EJECUTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        regresar.setText("REGRESAR");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel5.setText("MEDIA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(161, 161, 161))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(regresar)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(regresar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!"".equals(jTextField1.getText()) && !"".equals(jTextField2.getText())) {
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            Object[] objTabla = new Object[4];
            objTabla[0] = String.valueOf(proceso);
            objTabla[1] = jTextField1.getText();
            objTabla[2] = jTextField2.getText();
            objTabla[3] = "Preparado";
            modelo.addRow(objTabla);
            jTable1.setModel(modelo);
            jTextField1.setText(null);
            jTextField1.grabFocus();//enfocar
            jTextField2.setText(null);
            jTextField2.grabFocus();//enfocar
            proceso++;
        } else {
            JOptionPane.showMessageDialog(null, "No puede insertar procesos sin rafagas!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        new planificadores().setVisible(true);
        this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_regresarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Thread(new SJFNoExpropiativo.Hilo()).start(); //Crea un nuevo hilo
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private class Hilo implements Runnable {

        @Override
        public void run() {
           int  tiempo = parseInt((String) (jTable1.getValueAt(0, 2)));
            int tiempo1 = tiempo;
           int  media = tiempo;

            for (int a = 0; a < tiempo; a++) {
                tiempo1--;
                jTable1.setValueAt(tiempo1, 0, 2);
                Dormir();
            }
            jTable1.setValueAt("finalizado ", 0, 3);

//******************************************************************************
            recalcular();
            for (int i = 1; i < proceso - 1; i++) {
                tiempo = parseInt((String) (jTable1.getValueAt(i, 2)));
                tiempo1 = tiempo;
                if (i < proceso - 2) {
                    media = media + (media + tiempo);
                }
                for (int a = 0; a < tiempo; a++) {
                    tiempo1--;
                    jTable1.setValueAt(tiempo1, i, 2);
                    jTable1.setValueAt("ejecutando", i, 3);
                    Dormir();
                }
                jTable1.setValueAt("finalizado", i, 3);
            }
            media = media / proceso;
            jTextField3.setText(String.valueOf(media));
        }
    }

    public void recalcular() {
        for (int i = 0; i < proceso; i++) {
            for (int j = 1; j < proceso - 2; j++) {
                int rafaga = parseInt((String) (jTable1.getValueAt(j, 2)));
                int rafaga1 = parseInt((String) (jTable1.getValueAt(j+1, 2)));
                int tarribo = parseInt((String) (jTable1.getValueAt(j, 1)));
                int tarribo1 = parseInt((String) (jTable1.getValueAt(j+1, 1)));
                if (rafaga > rafaga1) {
                    int proc = parseInt((String) (jTable1.getValueAt(j, 0)));
                    int proc1 = parseInt((String) (jTable1.getValueAt(j+1, 0)));
                    jTable1.setValueAt(String.valueOf(proc1), j, 0);
                    jTable1.setValueAt(String.valueOf(proc), j + 1, 0);
                    jTable1.setValueAt(String.valueOf(tarribo1), j, 1);
                    jTable1.setValueAt(String.valueOf(tarribo), j + 1, 1);
                    jTable1.setValueAt(String.valueOf(rafaga1), j, 2);
                    jTable1.setValueAt(String.valueOf(rafaga), j + 1, 2);
                } else if (rafaga == rafaga1) {
                    if (tarribo > tarribo1) {
                       int proc = parseInt((String) (jTable1.getValueAt(j, 0)));
                    int proc1 = parseInt((String) (jTable1.getValueAt(j+1, 0)));
                        jTable1.setValueAt(String.valueOf(proc1), j, 0);
                        jTable1.setValueAt(String.valueOf(proc), j + 1, 0);
                        jTable1.setValueAt(String.valueOf(tarribo1), j, 1);
                        jTable1.setValueAt(String.valueOf(tarribo), j + 1, 1);
                        jTable1.setValueAt(String.valueOf(rafaga1), j, 2);
                        jTable1.setValueAt(String.valueOf(rafaga), j + 1, 2);
                    }
                }
            }
            
        }
    }

    public void Dormir() {
        try {
            Thread.sleep(100);
        } catch (InterruptedException ex) {
            Logger.getLogger(this.getClass()).log(Level.SEVERE, null, ex);
        }
    }

    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SJFNoExpropiativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SJFNoExpropiativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SJFNoExpropiativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SJFNoExpropiativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FCFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FCFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FCFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FCFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SJFNoExpropiativo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
